sylius_twig_hooks:
    hooks:
        # Shop layout customizations
        'sylius_shop.base#stylesheets':
            bitbag_inpost_styles:
                template: '@BitBagSyliusInPostPlugin/Shop/_styles.html.twig'
                priority: 0
        'sylius_shop.base#javascripts':
            bitbag_inpost_scripts:
                template: '@BitBagSyliusInPostPlugin/Shop/_scripts.html.twig'
                priority: 0

        # Shop checkout customization (uses the hook name directly from the template)
        'sylius_shop.checkout.select_shipping.before_form':
            bitbag_inpost_geowidget:
                template: '@BitBagSyliusInPostPlugin/InPostGeowidgetAssets.html.twig'
                priority: 0

        # Admin layout customizations
        'sylius_admin.base#stylesheets':
            bitbag_inpost_styles:
                template: '@BitBagSyliusInPostPlugin/Admin/_styles.html.twig'
                priority: 0
        'sylius_admin.base#javascripts':
            bitbag_inpost_scripts:
                template: '@BitBagSyliusInPostPlugin/Admin/_scripts.html.twig'
                priority: 0

        # Admin order show customization (uses the hook name directly from the template)
        'sylius_admin.order.show.sidebar':
            bitbag_inpost_geowidget:
                template: '@BitBagSyliusInPostPlugin/InPostGeowidgetAssets.html.twig'
                priority: 60